In [2]:
!pip install opencv-python
!pip install numpy

In [3]:
import cv2
import numpy as np

In [24]:
class VisionInput:
    frame = None
    
    def __init__(self, res, FOV): #a little confused abt the importance of FOV and resolution w/out calibration in the detection pipeline...? - Bhargav
        self.res = res
        self.FOV = FOV

    def calibrate():
        pass

    def start(self):
        global frame

        cap = cv2.VideoCapture(0)

        if not cap.isOpened():
            print("failed to init camera")
            exit

        while True:
            cv2.imshow('frame', self.getFrame(cap))
            if (cv2.waitKey(1) == ord('q')):
                break
            
            #for testing purposes
            if (cv2.waitKey(1) == ord('p')):
                print(self.getFrame(cap))
            
        cap.release()
        cv2.destroyAllWindows()
    
    def getFrame(self, cap):
        ret, frame = cap.read()
        if not ret:
            print('frame not reached')
            exit
        
        return np.asarray(frame)

In [25]:
#TEST BLOCK

vi = VisionInput(0, 0)
vi.start()

[[[133 135 137]
  [134 135 137]
  [133 132 135]
  ...
  [105 106 108]
  [104 106 108]
  [104 106 108]]

 [[135 134 139]
  [135 134 138]
  [127 126 129]
  ...
  [106 105 108]
  [106 105 108]
  [106 105 108]]

 [[129 131 133]
  [133 133 136]
  [135 135 137]
  ...
  [106 105 108]
  [105 104 107]
  [106 105 108]]

 ...

 [[138 121 116]
  [195 178 174]
  [179 161 158]
  ...
  [146 139 140]
  [145 138 139]
  [145 138 139]]

 [[180 162 159]
  [175 158 155]
  [178 160 157]
  ...
  [145 138 139]
  [145 138 139]
  [145 138 139]]

 [[176 159 154]
  [175 159 155]
  [175 160 157]
  ...
  [143 138 139]
  [143 138 139]
  [143 138 139]]]
[[[136 135 140]
  [137 136 141]
  [136 135 140]
  ...
  [105 107 109]
  [110 111 114]
  [ 97  99 101]]

 [[136 135 142]
  [136 135 141]
  [134 133 137]
  ...
  [104 106 108]
  [104 106 108]
  [103 104 107]]

 [[136 135 140]
  [136 135 140]
  [137 136 141]
  ...
  [105 106 108]
  [106 105 108]
  [106 105 108]]

 ...

 [[156 140 137]
  [187 172 169]
  [177 161 158]
  ..